### ISSUE TITLE
Unable to copy dlls

### ISSUE THREAD

**Issue by nojaf** [pdonald/nuget-webtargets#1]
Hello,

I'm using this package to build my code on Jenkins, but I'm  having a bit of a problem.
When building my MVC Website VS says it can't copy my dlls. In my Task Manager I'm seeing two instances of MSBuild.exe so one is blocking the other during development.

Is there a way to go around this? Use this package only for release mode f.ex.

**Comment by pdonald** [comment]
If you used the code from `README.md`, then this package is used only when Visual Studio is not installed:

``` xml
<Import Project="$(SolutionDir)\packages\MSBuild.Microsoft.VisualStudio.Web.targets.12.0.4\tools\VSToolsPath\WebApplications\Microsoft.WebApplication.targets" Condition="('$(VSToolsPath)' == '' Or !Exists('$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets')) And Exists('$(SolutionDir)\packages\MSBuild.Microsoft.VisualStudio.Web.targets.12.0.4\tools\VSToolsPath\WebApplications\Microsoft.WebApplication.targets')" />
```

More specifically

```
Condition="('$(VSToolsPath)' == '' Or !Exists('$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets'))
```
