### ISSUE TITLE
VS 2017

### ISSUE THREAD

**Issue by tomap** [pdonald/nuget-webtargets#15]
It seems it does not work with VS 2017 build tools.

I'm not sure of my analysis.

Any chance you could update this code to 2017

**Comment by CameronWills** [comment]
This nuget package is no longer needed in VS 2017.

You just need to install the **Visual Studio Build Tools** on your build server:

1. On the [Visual Studio download page](https://www.visualstudio.com/downloads/), expand **Other Tools and Frameworks** at the bottom of the page

2. Download the **Visual Studio build tools**

3. Run the installer and select to install **Visual Studio Build Tools 2017**

4. During the install, check the option for **Web Development Build Tools** 

This will install the required .targets in the `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0` folder

**Comment by tomap** [comment]
Thanks
