### ISSUE TITLE
Can't use with non-default Nuget `repositoryPath`

### ISSUE THREAD

**Issue by zlamma** [pdonald/nuget-webtargets#6]
Because of the `packages/` path hardcoded in:

https://github.com/pdonald/nuget-webtargets/commit/e1641ab993cb201873e2bc18d88bdc4e63c3b284#diff-19e2bf0045affb1f86c3649549c2f3b6R4

**Comment by Odeanathus** [comment]
This is the exact reason I can't currently use this package :-(

**Comment by zlamma** [comment]
The problem prevents the package from even installing, so the user can't just fix it post-install.

The only workaround is to install the 14.0.0 version and add the targets manually as per [the old instructions](https://github.com/pdonald/nuget-webtargets/blob/dddd7877f4f3bbe84c3f62ce033a060589e3841d/README.md#use).
